![Illustration of silhouetted heads](mentalhealth.jpg)

Does going to university in a different country affect your mental health? A Japanese international university surveyed its students in 2018 and published a study the following year that was approved by several ethical and regulatory boards.

The study found that international students have a higher risk of mental health difficulties than the general population, and that social connectedness (belonging to a social group) and acculturative stress (stress associated with joining a new culture) are predictive of depression.


Explore the `students` data using PostgreSQL to find out if you would come to a similar conclusion for international students and see if the length of stay is a contributing factor.

Here is a data description of the columns you may find helpful.

| Field Name    | Description                                      |
| ------------- | ------------------------------------------------ |
| `inter_dom`     | Types of students (international or domestic)   |
| `japanese_cate` | Japanese language proficiency                    |
| `english_cate`  | English language proficiency                     |
| `academic`      | Current academic level (undergraduate or graduate) |
| `age`           | Current age of student                           |
| `stay`          | Current length of stay in years                  |
| `todep`         | Total score of depression (PHQ-9 test)           |
| `tosc`          | Total score of social connectedness (SCS test)   |
| `toas`          | Total score of acculturative stress (ASISS test) |

In [77]:
SELECT stay,
       COUNT(*) AS count_int,
       ROUND(AVG(todep), 2) AS average_phq,
       ROUND(AVG(tosc), 2) AS average_scs,
       ROUND(AVG(toas), 2) AS average_as
FROM students 
WHERE inter_dom = 'Inter'
GROUP BY stay
ORDER BY stay DESC

   stay  count_int  average_phq  average_scs  average_as
0    10          1        13.00        32.00       50.00
1     8          1        10.00        44.00       65.00
2     7          1         4.00        48.00       45.00
3     6          3         6.00        38.00       58.67
4     5          1         0.00        34.00       91.00
5     4         14         8.57        33.93       87.71
6     3         46         9.09        37.13       78.00
7     2         39         8.28        37.08       77.67
8     1         95         7.48        38.11       72.80

In [78]:
-- Impacto da conectividade social e depresao , extra ao projeto inicial
SELECT
	CASE
		WHEN tosc <= 24 THEN 'Baixa conectividade social (0-24)'
		WHEN tosc BETWEEN 25 AND 36 THEN 'Media conectividade social (25-36)'
		ELSE 'Alta conectividade social +37'
	END AS conectividade_social,
	COUNT(*) AS Estudantes,
	ROUND(AVG(todep),2) Depressao_Media
FROM students
WHERE inter_dom ='Inter'
GROUP BY conectividade_social
ORDER BY conectividade_social DESC;

                 conectividade_social  estudantes  depressao_media
0  Media conectividade social (25-36)          54             8.93
1   Baixa conectividade social (0-24)          22            14.73
2       Alta conectividade social +37         125             6.49

In [79]:
-- Impacto do genero e religiao extra ao projeto inicial
SELECT gender,
	   religion,
	   COUNT(*) AS student_count,
	   ROUND(AVG(todep), 2) AS average_phq,
       ROUND(AVG(tosc), 2) AS average_scs,
       ROUND(AVG(toas), 2) AS average_as
FROM students
WHERE inter_dom = 'Inter'
GROUP BY gender, religion
ORDER BY gender, average_phq DESC

   gender religion  student_count  average_phq  average_scs  average_as
0  Female       No             86         8.92        35.49       79.66
1  Female      Yes             42         7.24        39.88       75.19
2    Male       No             40         7.73        37.83       73.28
3    Male      Yes             33         7.18        38.82       68.12

In [80]:
-- impacto de ser estudante internacional ou nativo ,extra ao projeto inicial
SELECT inter_dom,
       COUNT(*) AS total_students,
       ROUND(AVG(todep), 2) AS average_phq,
       ROUND(AVG(tosc), 2) AS average_scs,
       ROUND(AVG(toas), 2) AS average_as
FROM students
WHERE inter_dom IN ('Dom', 'Inter') -- a base de dados tem espaços em branco em vez de null
GROUP BY inter_dom;

  inter_dom  total_students  average_phq  average_scs  average_as
0     Inter             201         8.04        37.42       75.56
1       Dom              67         8.61        37.64       62.84

In [81]:
-- impacto de falar a linguagem fluetemente, extra ao projeto inicial
SELECT japanese_cate,
       COUNT(*) AS student_count,
       ROUND(AVG(todep), 2) AS average_phq,
       ROUND(AVG(tosc), 2) AS average_scs,
       ROUND(AVG(toas), 2) AS average_as
FROM students
WHERE inter_dom = 'Inter'
GROUP BY japanese_cate
ORDER BY average_phq

  japanese_cate  student_count  average_phq  average_scs  average_as
0          High             25         7.40        38.48       72.00
1           Low             91         7.91        36.99       76.65
2       Average             85         8.38        37.56       75.45

In [82]:
-- impacto da idade , extra ao projeto inicial
SELECT age,
	   COUNT(*) AS student_count,
       ROUND(AVG(todep), 2) AS average_phq,
       ROUND(AVG(tosc), 2) AS average_scs,
       ROUND(AVG(toas), 2) AS average_as
FROM students
WHERE inter_dom = 'Inter'
GROUP BY age
ORDER BY age DESC

    age  student_count  average_phq  average_scs  average_as
0    31              4         5.75        43.50       80.25
1    30              3         9.33        41.00       97.33
2    29              4         3.75        43.00       63.50
3    28              3         3.33        39.00       71.00
4    27              1        10.00        35.00       42.00
5    25              9         6.11        37.33       80.78
6    24              6         4.67        42.33       74.33
7    23             12         9.67        32.00       81.25
8    22             14         8.36        38.14       70.43
9    21             39         9.23        37.74       75.23
10   20             34         7.35        38.21       73.26
11   19             41         8.44        37.90       74.10
12   18             28         8.75        34.11       80.61
13   17              3         4.67        37.33       70.67